### ISSUE TITLE
Background is bright red for Simurai's duotone themes in gnome-terminal

### ISSUE THREAD

**Issue by nerdenough** [davidosomething/duotone-base16#1]
When converting Simurai's duotone themes (tried default and dark-earth), base00 is `#FF0000`, leading to the background of gnome-terminal being bright red after creating the theme through base16-builder or base16-builder-php.

![image](https://cloud.githubusercontent.com/assets/8467879/17427226/1227b572-5b33-11e6-8137-34c68f27f980.png)

**Comment by davidosomething** [comment]
want to submit a PR? I'm not sure what it should map to:
https://github.com/davidosomething/duotone-base16/blob/master/db16#L102-L105

**Comment by nerdenough** [comment]
Just submitted a PR that seems to fix the issue - though I am not sure how it will impact other templates if the `#FF0000` and `#FFFF00` are being used by them.
